### PR TITLE
cloudlink: upgrade.

### PR DESCRIPTION
**Pull request by AnessZurba**
This commit adds a lot of features to the script:
printing progress
date range
disk space checking
skip downloaded files
error handling
group by topic

I hope the code is still readable
I checked it's still working on Windows, didn't check on linux (but it should still work)

### CODE REVIEW

**Comment by AnessZurba** [comment]
@lanec is this repo still maintained?

**Comment by AnessZurba** [comment]
@lanec What does that entail exactly?
I'm not very familiar with Github etiquette

**Comment by lanec** [comment]
@AnessZurba It would put you in charge of what updates are accepted into the code.

**Comment by AnessZurba** [comment]
Yeah sure.

**Pull request merged**
